replicaCount: 1
image:
  repository: bwhazel/api
  pullPolicy: Always
imagePullSecrets: []
env:
  ASPNETCORE_ENVIRONMENT: "Production"
  AzureAD__TenantId: ""
  AzureAD__ClientId: ""
  AzureAD__ClientSecret: ""
  Secrets__KeyVault: ""
service:
  type: NodePort
  port: 80
ingress:
  enabled: true
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: api.bwhazel.co.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: api.bwhazel.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: api-bwhazel-secret
      hosts:
        - api.bwhazel.co.uk
        - api.bwhazel.uk
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
