apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bwhazel-api.fullname" . }}
  labels:
    {{- include "bwhazel-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bwhazel-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bwhazel-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{ range $key, $value := .Values.env }}
              - name: {{ $key | quote }}
                value: {{ $value | quote }}
            {{- end }}